#!/bin/bash
#Simple menu script tamplate

function menu {
  clear                                         #clear screen
  echo                                          #empty line
  echo -e "\t\t\tSystem Admin Menu\n"           #double tab to center title \t\t
  echo -e "\t1. Display disk space"             #menu
  echo -e "\t2. Display logged on users"
  echo -e "\t3. Display memory usage"
  echo -e "\t0. Exit menu\n\n"                  #double new line  \n\n
  echo -en "\t\tEnter option: "
  read -n 1 option                              #-n option to retrieve only one character
}

function diskspace {							# function to obtain disk space
  clear
  df -k
}

function whoson {								# function to obtain who is in the system
  clear
  who
}

function memusage {								# function to obtain memory usage
  clear
  cat /proc/meminfo | more
}

while [ 1 ]										# while loop the scan for user input			
do
  menu
  case $option in
  0)
     break;;
  1)
     diskspace;;
  2)
     whoson;;
  3)
     memusage;;
  *)
     clear
     echo "Wrong selection";;
  esac
  echo -en "\n\n\t\t\tPress aby key to continue"
  read -n 1 line
done
clear


